base_dir = 'Z:/Onkar Otari - Intern/Error_file/'

Error_process_login = base_dir + 'Error_Process_Login.csv'
Error_user_info = base_dir + 'Error_UserInfo.csv'
Error_refund_demand = base_dir + 'Error_Refund_Demand.csv'
Error_tax_deposit = base_dir + 'Error_TaxDeposit.csv'
Error_recent_file_return = base_dir + 'Error_RecentFiledReturn.csv'
Error_recent_form_filed = base_dir + 'Error_RecentFormFiled.csv'
Error_active_bank = base_dir + 'Error_ActiveBank.csv'
Error_inactive_bank = base_dir + 'Error_InactiveBank.csv'
Error_failed_bank = base_dir + 'Error_FailedBank.csv'
Error_juris_diction = base_dir + 'Error_JurisDicition.csv'
Error_src_business_salaried = base_dir + 'Error_Business_Salaried.csv'
Error_src_house_property = base_dir + 'Error_House_Property.csv'
Error_authorised_signature = base_dir + 'Error_AuthSign.csv'
Error_representative_asses = base_dir + 'Error_RepresentativeAsses.csv'
Error_demat_account = base_dir + 'Error_DematAccount.csv'
Error_active_demat_account = base_dir + 'Error_ActiveDematAccount.csv'

Error_fya = base_dir + 'Error_FYA.csv'
Error_fya_notice_count = base_dir + 'Error_FYA_CountNotice.csv'
Error_fya_notice_description = base_dir + 'Error_FYA_NoticeDescription.csv'
Error_fya_all_notices = base_dir + 'Error_FYA_AllNotices.csv'
Error_fya_notice_letter = base_dir + 'Error_FYA_NoticeLetter.csv'
Error_fya_notice_download = base_dir + 'Error_FYA_PDFDownload.csv'

Error_fyi = base_dir + 'Error_FYI.csv'
Error_fyi_count = base_dir + 'Error_FYI_NoticeCount.csv'
Error_fyi_notice_description = base_dir + 'Error_FYI_NoticeDescription.csv'
Error_fyi_all_notices = base_dir + 'Error_FYI_AllNotices.csv'
Error_fyi_notice_letter = base_dir + 'Error_FYI_NoticeLetter.csv'
Error_fyi_notice_download = base_dir + 'Error_FYI_NoticeDownload.csv'
Error_direct_notice_download_path = base_dir + 'Error_FYI_DirectNoticeDownload.csv'